feat - responsive navbar
iambizan/glitterCSS pull request #7
Opened 2022-02-02 18:14 UTC by iambizan

2022-02-02 18:43 UTC, yash9263 commented on components/navbar.css
> +.nav-links > li > a {
can give `<a>` tag a name like `nav-link` instead of nesting two levels down

2022-02-02 18:44 UTC, yash9263 commented
looks good to me

2022-02-02 18:45 UTC, Bibin-Antony approved these changes

2022-02-02 18:47 UTC, yash9263 approved these changes

2022-02-02 18:47 UTC, Bibin-Antony requested changes

2022-02-02 18:47 UTC, Bibin-Antony commented on components/navbar.css
> +  .nav-links li {
you could add a hover effect on the nav labels. For home Docs and the rest.

2022-02-03 04:32 UTC, SukanyaSen530 approved these changes
Looks Good to be merged

2022-02-03 06:54 UTC, iambizan commented on components/navbar.css
> +.nav-links > li > a {
refactored

2022-02-03 06:55 UTC, iambizan commented on components/navbar.css
> +  .nav-links li {
it is already there, as you can see in the preview. Thanks for input.

2022-02-03 06:56 UTC, merged

2022-02-03 19:35 UTC, sandeepkumardev commented
all good 👍